<?xml version="1.0" encoding="UTF-8"?>
<TestRun id="1c41d5ca-79e0-4bc7-b6e7-b3c40d9e7bce" name="Cwoo@CWOO-PC 2011-04-17 18:16:05" runUser="Cwoo-PC\Cwoo" xmlns="http://microsoft.com/schemas/VisualStudio/TeamTest/2010">
  <TestSettings name="Local" id="49e49dd0-324f-478a-ab30-f3aeba0afd51">
    <Description>These are default test settings for a local test run.</Description>
    <Deployment enabled="false" runDeploymentRoot="Cwoo_CWOO-PC 2011-04-17 18_16_05">
      <DeploymentItem filename="C:\Users\Cwoo\Desktop\SvnLog\SvnDomainModel\bin\Debug\SvnDomainModel.dll" />
    </Deployment>
    <Execution>
      <TestTypeSpecific />
      <AgentRule name="Execution Agents">
      </AgentRule>
    </Execution>
  </TestSettings>
  <Times creation="2011-04-17T18:16:05.6351748+01:00" queuing="2011-04-17T18:16:05.7261800+01:00" start="2011-04-17T18:16:05.7441810+01:00" finish="2011-04-17T18:16:05.9571932+01:00" />
  <ResultSummary outcome="Failed">
    <Counters total="1" executed="1" error="0" failed="1" timeout="0" aborted="0" inconclusive="0" passedButRunAborted="0" notRunnable="0" notExecuted="0" disconnected="0" warning="0" passed="0" completed="0" inProgress="0" pending="0" />
  </ResultSummary>
  <TestDefinitions>
    <UnitTest name="TestSvnProncessThrowsAnErrorWhenTheStandardErrorLogHasSomthingInIt" storage="c:\users\cwoo\desktop\svnlog\testsvndomainmodel\bin\debug\testsvndomainmodel.dll" id="b9c48b81-c181-0ea3-d9f9-8ae341a98518">
      <Execution id="dea3acf2-9617-4228-bd8a-e4960b55ed08" />
      <TestMethod codeBase="C:/Users/Cwoo/Desktop/SvnLog/TestSvnDomainModel/bin/Debug/TestSvnDomainModel.DLL" adapterTypeName="Microsoft.VisualStudio.TestTools.TestTypes.Unit.UnitTestAdapter, Microsoft.VisualStudio.QualityTools.Tips.UnitTest.Adapter, Version=10.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" className="TestSvnDomainModel.TestSvnLog, TestSvnDomainModel, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null" name="TestSvnProncessThrowsAnErrorWhenTheStandardErrorLogHasSomthingInIt" />
    </UnitTest>
  </TestDefinitions>
  <TestLists>
    <TestList name="Results Not in a List" id="8c84fa94-04c1-424b-9868-57a2d4851a1d" />
    <TestList name="All Loaded Results" id="19431567-8539-422a-85d7-44ee4e166bda" />
  </TestLists>
  <TestEntries>
    <TestEntry testId="b9c48b81-c181-0ea3-d9f9-8ae341a98518" executionId="dea3acf2-9617-4228-bd8a-e4960b55ed08" testListId="8c84fa94-04c1-424b-9868-57a2d4851a1d" />
  </TestEntries>
  <Results>
    <UnitTestResult executionId="dea3acf2-9617-4228-bd8a-e4960b55ed08" testId="b9c48b81-c181-0ea3-d9f9-8ae341a98518" testName="TestSvnProncessThrowsAnErrorWhenTheStandardErrorLogHasSomthingInIt" computerName="CWOO-PC" duration="00:00:00.0285372" startTime="2011-04-17T18:16:05.7391807+01:00" endTime="2011-04-17T18:16:05.9461925+01:00" testType="13cdc9d9-ddb5-4fa4-a97d-d965ccfc6d4b" outcome="Failed" testListId="8c84fa94-04c1-424b-9868-57a2d4851a1d" relativeResultsDirectory="dea3acf2-9617-4228-bd8a-e4960b55ed08">
      <Output>
        <ErrorInfo>
          <Message>Test method TestSvnDomainModel.TestSvnLog.TestSvnProncessThrowsAnErrorWhenTheStandardErrorLogHasSomthingInIt threw exception System.ComponentModel.Win32Exception, but exception SvnDomainModel.Svn+SvnProcess+SvnException was expected. Exception message: System.ComponentModel.Win32Exception: The system cannot find the file specified</Message>
          <StackTrace>    at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at SvnDomainModel.Svn.SvnProcess.ExecuteCommand() in C:\Users\Cwoo\Desktop\SvnLog\SvnDomainModel\Svn.vb:line 237
   at TestSvnDomainModel.TestSvnLog.TestSvnProncessThrowsAnErrorWhenTheStandardErrorLogHasSomthingInIt() in C:\Users\Cwoo\Desktop\SvnLog\TestSvnDomainModel\TestSvnLog.cs:line 87
</StackTrace>
        </ErrorInfo>
      </Output>
    </UnitTestResult>
  </Results>
</TestRun>