<?xml version="1.0" encoding="UTF-8"?>
<TestRun id="fedd1a79-3ffa-48e2-83e7-540ebe902232" name="Cwoo@CWOO-PC 2011-04-17 18:24:46" runUser="Cwoo-PC\Cwoo" xmlns="http://microsoft.com/schemas/VisualStudio/TeamTest/2010">
  <TestSettings name="Local" id="49e49dd0-324f-478a-ab30-f3aeba0afd51">
    <Description>These are default test settings for a local test run.</Description>
    <Deployment enabled="false" runDeploymentRoot="Cwoo_CWOO-PC 2011-04-17 18_24_46">
      <DeploymentItem filename="C:\Users\Cwoo\Desktop\SvnLog\SvnDomainModel\bin\Debug\SvnDomainModel.dll" />
    </Deployment>
    <Execution>
      <TestTypeSpecific />
      <AgentRule name="Execution Agents">
      </AgentRule>
    </Execution>
  </TestSettings>
  <Times creation="2011-04-17T18:24:46.4596035+01:00" queuing="2011-04-17T18:24:49.3503204+01:00" start="2011-04-17T18:24:49.5999208+01:00" finish="2011-04-17T18:24:55.2131381+01:00" />
  <ResultSummary outcome="Failed">
    <Counters total="1" executed="1" error="0" failed="1" timeout="0" aborted="0" inconclusive="0" passedButRunAborted="0" notRunnable="0" notExecuted="0" disconnected="0" warning="0" passed="0" completed="0" inProgress="0" pending="0" />
  </ResultSummary>
  <TestDefinitions>
    <UnitTest name="TestSvnProncessThrowsAnErrorWhenTheStandardErrorLogHasSomthingInIt" storage="c:\users\cwoo\desktop\svnlog\testsvndomainmodel\bin\debug\testsvndomainmodel.dll" id="b9c48b81-c181-0ea3-d9f9-8ae341a98518">
      <Execution id="5210df64-b054-4326-839f-1375b69a56ed" />
      <TestMethod codeBase="C:/Users/Cwoo/Desktop/SvnLog/TestSvnDomainModel/bin/Debug/TestSvnDomainModel.DLL" adapterTypeName="Microsoft.VisualStudio.TestTools.TestTypes.Unit.UnitTestAdapter, Microsoft.VisualStudio.QualityTools.Tips.UnitTest.Adapter, Version=10.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" className="TestSvnDomainModel.TestSvnLog, TestSvnDomainModel, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null" name="TestSvnProncessThrowsAnErrorWhenTheStandardErrorLogHasSomthingInIt" />
    </UnitTest>
  </TestDefinitions>
  <TestLists>
    <TestList name="Results Not in a List" id="8c84fa94-04c1-424b-9868-57a2d4851a1d" />
    <TestList name="All Loaded Results" id="19431567-8539-422a-85d7-44ee4e166bda" />
  </TestLists>
  <TestEntries>
    <TestEntry testId="b9c48b81-c181-0ea3-d9f9-8ae341a98518" executionId="5210df64-b054-4326-839f-1375b69a56ed" testListId="8c84fa94-04c1-424b-9868-57a2d4851a1d" />
  </TestEntries>
  <Results>
    <UnitTestResult executionId="5210df64-b054-4326-839f-1375b69a56ed" testId="b9c48b81-c181-0ea3-d9f9-8ae341a98518" testName="TestSvnProncessThrowsAnErrorWhenTheStandardErrorLogHasSomthingInIt" computerName="CWOO-PC" duration="00:00:03.8794986" startTime="2011-04-17T18:24:49.7941215+01:00" endTime="2011-04-17T18:24:55.0811305+01:00" testType="13cdc9d9-ddb5-4fa4-a97d-d965ccfc6d4b" outcome="Failed" testListId="8c84fa94-04c1-424b-9868-57a2d4851a1d" relativeResultsDirectory="5210df64-b054-4326-839f-1375b69a56ed">
      <Output>
        <ErrorInfo>
          <Message>Test method TestSvnDomainModel.TestSvnLog.TestSvnProncessThrowsAnErrorWhenTheStandardErrorLogHasSomthingInIt threw exception System.ComponentModel.Win32Exception, but exception SvnDomainModel.Svn+SvnProcess+SvnException was expected. Exception message: System.ComponentModel.Win32Exception: The system cannot find the file specified</Message>
          <StackTrace>    at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at SvnDomainModel.Svn.SvnProcess.ExecuteCommand() in C:\Users\Cwoo\Desktop\SvnLog\SvnDomainModel\Svn.vb:line 237
   at TestSvnDomainModel.TestSvnLog.TestSvnProncessThrowsAnErrorWhenTheStandardErrorLogHasSomthingInIt() in C:\Users\Cwoo\Desktop\SvnLog\TestSvnDomainModel\TestSvnLog.cs:line 87
</StackTrace>
        </ErrorInfo>
      </Output>
    </UnitTestResult>
  </Results>
</TestRun>